/**
 * Comprehensive blocklist of known disposable / temporary email domains.
 * Prevents creation of throwaway accounts that degrade platform integrity.
 */
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  "0-mail.com",
  "10minutemail.be",
  "10minutemail.co.uk",
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemailbox.com",
  "20minutemail.com",
  "2prong.com",
  "anonbox.net",
  "anonymbox.com",
  "antichef.com",
  "antichef.net",
  "baxomale.ht.cx",
  "bccto.me",
  "brefmail.com",
  "burnermail.io",
  "cachedot.net",
  "crazymailing.com",
  "curryjunk.com",
  "dayrep.com",
  "deadaddress.com",
  "dispostable.com",
  "drdrb.net",
  "dropmail.me",
  "emailondeck.com",
  "emailtemporario.com.br",
  "emltmp.com",
  "fakemailgenerator.com",
  "filzmail.com",
  "generator.email",
  "getairmail.com",
  "getnada.com",
  "grr.la",
  "guerrillamail.biz",
  "guerrillamail.block",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "harakirimail.com",
  "inboxbear.com",
  "inboxkitten.com",
  "invalids.email",
  "jetable.org",
  "kasmail.com",
  "koszmail.pl",
  "linshiyouxiang.net",
  "luxusmail.org",
  "mail-temporaire.fr",
  "mailcatch.com",
  "maildrop.cc",
  "mailexpire.com",
  "mailimate.com",
  "mailinator.com",
  "mailinator.net",
  "mailinator2.com",
  "mailnesia.com",
  "mailnull.com",
  "mailsac.com",
  "mailtemp.top",
  "mailtothis.com",
  "meltmail.com",
  "mintemail.com",
  "mohmal.com",
  "mohmal.in",
  "mytemp.email",
  "nada.ltd",
  "nada.org",
  "nospam.ze.tc",
  "nowmymail.com",
  "oneoffmail.com",
  "our-fake-mail.com",
  "owlymail.com",
  "pokemail.net",
  "sharklasers.com",
  "shieldedmail.com",
  "shortmail.net",
  "spam4.me",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spamex.com",
  "spamevader.com",
  "spamfree24.org",
  "spamgourmet.com",
  "spamhole.com",
  "spaml.de",
  "spaminator.de",
  "temp-mail.org",
  "temp-mail.io",
  "temp-mail.ru",
  "tempail.com",
  "tempm.com",
  "tempmail.alt",
  "tempmail.co",
  "tempmail.com",
  "tempmail.de",
  "tempmail.io",
  "tempmail.net",
  "tempmail.us",
  "tempmailaddress.com",
  "tempmailgen.com",
  "tempr.email",
  "throwawaymail.com",
  "trashmail.com",
  "trashmail.de",
  "trashmail.net",
  "trashmail.org",
  "trbvm.com",
  "vmani.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "zoemail.org",
]);

/**
 * Validates whether an email address uses a known temporary/disposable domain.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || typeof email !== "string") return false;

  const parts = email.trim().toLowerCase().split("@");
  if (parts.length !== 2) return false;

  const domain = parts[1];
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
